import { WebClient } from '@slack/web-api';
import { securityAuditLogger } from './auditLogger';

interface SlackNotification {
  channel?: string;
  text: string;
  blocks?: any[];
  username?: string;
  icon_emoji?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  category: 'wellness' | 'achievement' | 'alert' | 'esg' | 'certificate' | 'message';
}

interface WebhookPayload {
  channel?: string;
  text: string;
  username?: string;
  icon_emoji?: string;
  blocks?: any[];
}

class SlackNotificationService {
  private webhookUrl: string | null;
  private botToken: string | null;
  private slackClient: WebClient | null;

  constructor() {
    this.webhookUrl = process.env.SLACK_WEBHOOK_URL || null;
    this.botToken = process.env.SLACK_BOT_TOKEN || null;
    this.slackClient = this.botToken ? new WebClient(this.botToken) : null;
  }

  private async sendWebhook(payload: WebhookPayload): Promise<boolean> {
    if (!this.webhookUrl) {
      console.log('Slack webhook not configured, skipping notification:', payload.text);
      return false;
    }

    try {
      const response = await fetch(this.webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error(`Webhook failed: ${response.status} ${response.statusText}`);
      }

      console.log('✅ Slack notification sent:', payload.text);
      return true;
    } catch (error) {
      console.error('❌ Failed to send Slack notification:', error);
      return false;
    }
  }

  private getPriorityEmoji(priority: string): string {
    switch (priority) {
      case 'urgent': return '🚨';
      case 'high': return '⚠️';
      case 'medium': return '📢';
      case 'low': return '💡';
      default: return '📝';
    }
  }

  private getCategoryEmoji(category: string): string {
    switch (category) {
      case 'wellness': return '🌟';
      case 'achievement': return '🏆';
      case 'alert': return '⚡';
      case 'esg': return '📊';
      case 'certificate': return '🎓';
      case 'message': return '💌';
      default: return '📋';
    }
  }

  async sendNotification(notification: SlackNotification): Promise<boolean> {
    const priorityEmoji = this.getPriorityEmoji(notification.priority);
    const categoryEmoji = this.getCategoryEmoji(notification.category);
    
    const payload: WebhookPayload = {
      channel: notification.channel,
      text: `${priorityEmoji} ${categoryEmoji} ${notification.text}`,
      username: notification.username || 'EchoDeed™ Wellness Platform',
      icon_emoji: notification.icon_emoji || ':heart:',
      blocks: notification.blocks,
    };

    return await this.sendWebhook(payload);
  }

  // AI Prediction Engine Notifications
  async sendWellnessAlert(prediction: any): Promise<void> {
    const riskLevel = prediction.riskLevel || 'medium';
    const department = prediction.department || 'team';
    const confidence = Math.round((prediction.confidence || 0.85) * 100);
    
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `🧠 AI Wellness Alert: ${riskLevel.toUpperCase()} Risk Detected`,
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Department:* ${department}`
          },
          {
            type: 'mrkdwn',
            text: `*Risk Level:* ${riskLevel.charAt(0).toUpperCase() + riskLevel.slice(1)}`
          },
          {
            type: 'mrkdwn',
            text: `*Confidence:* ${confidence}%`
          },
          {
            type: 'mrkdwn',
            text: `*Prediction:* ${prediction.prediction || 'Team wellness support needed'}`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Recommended Actions:*\n${prediction.recommendations?.slice(0, 3).map((rec: string) => `• ${rec}`).join('\n') || '• Schedule team check-in\n• Provide wellness resources\n• Monitor team morale'}`
        }
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `🤖 Generated by EchoDeed™ AI Prediction Engine | Impact: ${prediction.estimatedImpact || 'High'}`
          }
        ]
      }
    ];

    await this.sendNotification({
      text: `AI detected ${riskLevel} wellness risk in ${department} with ${confidence}% confidence. Immediate intervention recommended.`,
      blocks,
      priority: riskLevel === 'high' ? 'urgent' : 'high',
      category: 'alert',
    });
  }

  // Global Wellness Heatmap Notifications
  async sendHeatmapAlert(data: any): Promise<void> {
    const criticalDepartments = data.departments?.filter((d: any) => d.riskLevel === 'high').length || 0;
    const overallScore = data.overallWellnessScore || 75;

    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🗺️ Global Wellness Heatmap Update',
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Overall Wellness Score:* ${overallScore}/100`
          },
          {
            type: 'mrkdwn',
            text: `*Critical Departments:* ${criticalDepartments}`
          },
          {
            type: 'mrkdwn',
            text: `*Total Responses:* ${data.totalResponses || 156} employees`
          },
          {
            type: 'mrkdwn',
            text: `*Last Updated:* ${new Date().toLocaleTimeString()}`
          }
        ]
      }
    ];

    if (criticalDepartments > 0) {
      await this.sendNotification({
        text: `🚨 Wellness Alert: ${criticalDepartments} departments showing critical wellness levels. Overall score: ${overallScore}/100`,
        blocks,
        priority: 'urgent',
        category: 'alert',
      });
    }
  }

  // Smart Kindness Matching Notifications
  async sendMatchingSuccess(match: any): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🎯 Perfect Kindness Match Found!',
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Opportunity:* ${match.title || 'Community Support'}`
          },
          {
            type: 'mrkdwn',
            text: `*Match Accuracy:* ${match.accuracy || 94}%`
          },
          {
            type: 'mrkdwn',
            text: `*Participants:* ${match.participants || 12} employees`
          },
          {
            type: 'mrkdwn',
            text: `*Impact Score:* ${match.impactScore || 8.7}/10`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Description:* ${match.description || 'A perfectly matched opportunity to make a positive impact in your community.'}`
        }
      }
    ];

    await this.sendNotification({
      text: `🎯 AI found perfect kindness match: "${match.title}" with ${match.accuracy}% accuracy for ${match.participants} employees!`,
      blocks,
      priority: 'medium',
      category: 'achievement',
    });
  }

  // ESG Impact Reporting Notifications
  async sendESGReport(report: any): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `📊 ${report.title || 'ESG Impact Report'} Ready`,
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Overall Score:* ${report.totalScore || 87.5}/100`
          },
          {
            type: 'mrkdwn',
            text: `*Industry Ranking:* #${report.industryRanking || 12}`
          },
          {
            type: 'mrkdwn',
            text: `*Period:* ${report.period || 'Q4 2024'}`
          },
          {
            type: 'mrkdwn',
            text: `*Status:* ${report.status || 'Final'}`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Key Achievements:*\n${report.achievements?.slice(0, 3).map((achievement: string) => `✅ ${achievement}`).join('\n') || '✅ Exceeded carbon offset targets\n✅ 94% wellness participation\n✅ B-Corp certification received'}`
        }
      },
      {
        type: 'actions',
        elements: [
          {
            type: 'button',
            text: {
              type: 'plain_text',
              text: 'Download Report 📥',
            },
            url: report.downloadUrl || '#',
            style: 'primary'
          }
        ]
      }
    ];

    await this.sendNotification({
      text: `📊 ESG Report "${report.title}" complete! Score: ${report.totalScore}/100, Industry Rank: #${report.industryRanking}`,
      blocks,
      priority: 'high',
      category: 'esg',
    });
  }

  // Blockchain Certificate Notifications
  async sendCertificateAchievement(certificate: any): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `🏆 ${certificate.level || 'Gold'} Certificate Earned!`,
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Achievement:* ${certificate.title || 'Kindness Pioneer'}`
          },
          {
            type: 'mrkdwn',
            text: `*Level:* ${certificate.level || 'Gold'}`
          },
          {
            type: 'mrkdwn',
            text: `*Rarity:* ${certificate.rarity || 12.3}% of users`
          },
          {
            type: 'mrkdwn',
            text: `*Blockchain:* ${certificate.blockchainNetwork || 'EchoDeed Chain'}`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Impact Metrics:*\n• 👥 ${certificate.impactMetrics?.peopleHelped || 134} people helped\n• ⏰ ${certificate.impactMetrics?.hoursContributed || 89} hours contributed\n• 🌍 ${certificate.impactMetrics?.co2Offset || 245}kg CO2 offset`
        }
      },
      {
        type: 'actions',
        elements: [
          {
            type: 'button',
            text: {
              type: 'plain_text',
              text: 'View Certificate 🎓',
            },
            url: certificate.certificateUrl || '#',
            style: 'primary'
          },
          {
            type: 'button',
            text: {
              type: 'plain_text',
              text: 'Verify Blockchain 🔗',
            },
            url: certificate.verificationUrl || '#'
          }
        ]
      }
    ];

    await this.sendNotification({
      text: `🏆 Congratulations! ${certificate.level} certificate "${certificate.title}" earned and blockchain-verified! Only ${certificate.rarity}% of users achieve this.`,
      blocks,
      priority: 'high',
      category: 'certificate',
    });
  }

  // Time-Locked Message Notifications
  async sendMessageDelivered(message: any): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '⏰ Time-Locked Wellness Message Delivered!',
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Subject:* ${message.subject || 'Weekly Motivation'}`
          },
          {
            type: 'mrkdwn',
            text: `*Recipients:* ${message.recipientCount || 1} people`
          },
          {
            type: 'mrkdwn',
            text: `*Category:* ${message.category || 'encouragement'}`
          },
          {
            type: 'mrkdwn',
            text: `*Scheduled:* ${message.scheduledDelay || '3 days ago'}`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Message Preview:* "${message.content?.substring(0, 150) || 'Your positive impact makes a real difference...'}${message.content?.length > 150 ? '...' : ''}"`
        }
      }
    ];

    await this.sendNotification({
      text: `⏰ Time-locked message "${message.subject}" successfully delivered to ${message.recipientCount} recipients! Perfect timing achieved.`,
      blocks,
      priority: 'medium',
      category: 'message',
    });
  }

  // General Achievement Notifications
  async sendGeneralAchievement(data: any): Promise<void> {
    await this.sendNotification({
      text: `🎉 ${data.message || 'New achievement unlocked!'} - ${data.details || 'Great work on your wellness journey!'}`,
      priority: data.priority || 'medium',
      category: 'achievement',
    });
  }

  /**
   * 🔒 SECURE Crisis Detection Notifications with Data Minimization
   * 
   * Implements COPPA/FERPA compliant notifications with:
   * - Minimal PII exposure
   * - Redacted content
   * - Audit logging
   * - Professional context only
   */
  async sendCrisisAlert(alert: any): Promise<void> {
    const urgencyEmoji = alert.safetyLevel === 'Crisis' ? '🚨' : '⚠️';
    const actionLevel = alert.safetyLevel === 'Crisis' ? 'IMMEDIATE ACTION REQUIRED' : 'PROFESSIONAL REVIEW NEEDED';
    
    // 🔒 DATA MINIMIZATION: Create redacted content
    const redactedContent = this.redactSensitiveContent({
      detectedKeywords: alert.detectedKeywords,
      postId: alert.postId,
      schoolId: alert.schoolId,
      safetyLevel: alert.safetyLevel
    });
    
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `${urgencyEmoji} ${alert.safetyLevel.toUpperCase()} ALERT - Student Support Required`,
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Reference:* ${this.generateSecureReference(alert.postId)}`
          },
          {
            type: 'mrkdwn',
            text: `*School:* ${this.obfuscateSchoolId(alert.schoolId)}`
          },
          {
            type: 'mrkdwn',
            text: `*Safety Level:* ${alert.safetyLevel}`
          },
          {
            type: 'mrkdwn',
            text: `*Crisis Score:* ${alert.crisisScore}/100`
          },
          {
            type: 'mrkdwn',
            text: `*Urgency:* ${alert.urgencyLevel.toUpperCase()}`
          },
          {
            type: 'mrkdwn',
            text: `*Alert Time:* ${new Date().toLocaleString()}`
          }
        ]
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Content Assessment:* ${redactedContent.summary}`
        }
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Professional Action:* ${alert.recommendedAction}`
        }
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `🔒 *Privacy Notice:* Content redacted per COPPA/FERPA requirements. Full details available in secure counselor dashboard.`
          }
        ]
      }
    ];

    // Add emergency resources for crisis-level alerts (no PII)
    if (alert.emergencyResources && alert.emergencyResources.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Emergency Resources Available:*\n${alert.emergencyResources.slice(0,2).map((resource: any) => `• ${resource.title} (${resource.availableHours})`).join('\n')}`
        }
      });
    }

    // Add action buttons for counselors
    blocks.push({
      type: 'actions',
      elements: [
        {
          type: 'button',
          text: {
            type: 'plain_text',
            text: 'View Crisis Queue 🏥',
          },
          url: '#', // Would link to counselor dashboard
          style: 'danger'
        },
        {
          type: 'button',
          text: {
            type: 'plain_text',
            text: 'Emergency Protocol 📋',
          },
          url: '#' // Would link to crisis response protocol
        }
      ]
    });

    const notificationResult = await this.sendNotification({
      text: `${urgencyEmoji} ${actionLevel}: ${alert.safetyLevel} assessment completed. Professional review required.`,
      blocks,
      priority: alert.safetyLevel === 'Crisis' ? 'urgent' : 'high',
      category: 'alert',
    });
    
    // 🔒 AUDIT: Log the redacted notification
    await securityAuditLogger.logSlackNotification({
      postId: alert.postId,
      schoolId: alert.schoolId,
      safetyLevel: alert.safetyLevel,
      messageType: alert.safetyLevel === 'Crisis' ? 'CRISIS_ALERT' : 'HIGH_RISK_ALERT',
      redactedContent: redactedContent.summary,
      success: notificationResult !== null,
      errorMessage: notificationResult === null ? 'Slack notification failed' : undefined
    });
  }

  /**
   * 🔒 DATA MINIMIZATION HELPERS
   * 
   * These methods implement COPPA/FERPA compliant data minimization
   * by redacting PII and providing only necessary professional context.
   */
  
  private redactSensitiveContent(data: {
    detectedKeywords: string[];
    postId: string;
    schoolId: string;
    safetyLevel: string;
  }): { summary: string; indicators: string[] } {
    // Create professional assessment without exposing student content
    const riskIndicators = data.detectedKeywords?.length || 0;
    const assessmentLevel = data.safetyLevel === 'Crisis' ? 'immediate intervention' : 'professional review';
    
    return {
      summary: `Assessment indicates ${assessmentLevel} needed. ${riskIndicators} risk indicators identified. Content secured per privacy requirements.`,
      indicators: data.detectedKeywords?.map(k => k.split(' ')[0] + '***') || [] // Partial redaction
    };
  }
  
  private generateSecureReference(postId: string): string {
    // Create a secure reference that can't be used to identify the student
    const hash = postId.substring(0, 8).toUpperCase();
    return `REF-${hash}`;
  }
  
  private obfuscateSchoolId(schoolId: string): string {
    // Show only enough to identify which counseling team needs to respond
    if (!schoolId || schoolId.length < 4) return 'SCH-***';
    return schoolId.substring(0, 4).toUpperCase() + '***';
  }

  // System Health Notifications
  async sendSystemAlert(alert: any): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '⚠️ EchoDeed™ System Alert',
        }
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Alert:* ${alert.message || 'System notification'}\n*Severity:* ${alert.severity || 'Medium'}\n*Time:* ${new Date().toLocaleTimeString()}`
        }
      }
    ];

    await this.sendNotification({
      text: `⚠️ System Alert: ${alert.message}`,
      blocks,
      priority: alert.severity === 'High' ? 'urgent' : 'high',
      category: 'alert',
    });
  }
}

export const slackNotifications = new SlackNotificationService();